[userinfo]
key = 
email = 



[fields]
# 查询字段（可自定义）
fields = host,protocol,ip,port,title,domain,country

[size]
# 每页返回数量
size = 100

[full]
# 是否搜索全部数据（true 或 false）
full = true

[excel]
# 批量查询时是否合并到一个 Excel 文件（on/off）
sheet_merge = on

[page]
# 起始页（包含）
start_page = 1
# 结束页（不包含），即查询第1页到第4页
end_page = 5

[logger]
# 日志开关
logger = on

[fast_check]
# 存活检测开关（本脚本未使用，但库可能需要）
check_alive = off
timeout = 8